<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Pulse.Campaigns.Application/Pulse.Campaigns.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Shared/Pulse.Contracts/Pulse.Contracts.csproj" />
  </ItemGroup>
</Project>
