<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Pulse.Contacts.Application/Pulse.Contacts.Application.csproj" />
    <ProjectReference Include="../Pulse.Contacts.Infrastructure/Pulse.Contacts.Infrastructure.csproj" />
  </ItemGroup>
</Project>
